name: Auto PR to production

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: npm install

      - name: Build du backend
        run: |
          cd backend/
          npm install
          npm run build

      - name: Build du frontend
        run: |
          cd frontend/
          npm install
          npm run build

  create-pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important pour avoir l'historique complet

      - name: Configurer Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Vérifier si une PR existe déjà
      - name: Vérifier les PRs existantes
        id: check-pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/pulls
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository.name }}
          head: sync-main-to-production
          base: production
          state: open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      # Créer et pousser la branche uniquement si aucune PR n'existe
      - name: Créer la branche de synchronisation
        if: steps.check-pr.outputs.status != '200'
        run: |
          git fetch origin production
          git checkout -b sync-main-to-production origin/main
          git push -f origin sync-main-to-production

      # Créer la PR uniquement si elle n'existe pas déjà
      - name: Créer la Pull Request
        if: steps.check-pr.outputs.status != '200'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: production
          branch: sync-main-to-production
          title: "🔄 Auto PR: Sync main → production"
          body: |
            Cette PR est générée automatiquement pour synchroniser main vers production.
            - Les builds ont été vérifiés avec succès
            - Merci de revoir les changements avant d'approuver
          labels: "automated-pr"
          reviewers: "Safirl"

  cleanup:
    needs: [create-pr]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Nettoyer les anciennes branches
        if: ${{ failure() }}
        run: |
          git push origin --delete sync-main-to-production || true
