name: Auto PR to production

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: npm install

      - name: Build du backend
        run: |
          cd backend/
          npm install
          npm run build

      - name: Build du frontend
        run: |
          cd frontend/
          npm install
          npm run build

  create-pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Vérifier s'il y a des différences entre main et production
      - name: Vérifier les différences
        id: check-diff
        run: |
          git fetch origin production
          git diff origin/production...main --quiet || echo "has_changes=true" >> $GITHUB_OUTPUT

      # Créer la PR seulement s'il y a des différences
      - name: Créer la Pull Request
        if: steps.check-diff.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: production
          title: "🔄 Auto PR: Sync main → production"
          body: |
            Cette PR est générée automatiquement pour synchroniser main vers production.
            - Les builds ont été vérifiés avec succès
            - Merci de revoir les changements avant d'approuver
          labels: "automated-pr"
          reviewers: "Safirl"
          delete-branch: true

  cleanup:
    needs: [create-pr]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Nettoyer les anciennes branches
        if: ${{ failure() }}
        run: |
          git push origin --delete pr-* || true
