name: Build & Test

on:
  pull_request:
    branches:
      - production
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production-approval

    services:
      mongodb:
        image: mongo:8.0.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping:1})'" 
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 5
    env:
      MONGO_URI: ${{ vars.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_FOLDER: ${{ vars.CLOUDINARY_FOLDER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install && cd backend && npm install && cd ../frontend && npm install && cd ..

      - name: Build the project
        run: cd backend/ && npm run build && cd ../frontend && npm run build

      - name: Run tests
        run: cd backend/ && npm test
